[tool.poetry]
name = "pyartemis"
packages = [
    { include = "artemis" }
]
version = "0.1.6"
description = "A Python package with explanation methods for extraction of feature interactions from predictive models"
readme = "README.md"
documentation = "https://pyartemis.github.io/"
keywords = ["interactions", "xai", "Explainable Artificial Intelligence", "explanations", "machine learning", "iml", "Interpretable Machine Learning"]
authors = ["Artur Żółkowski <artur.zolkowski@wp.pl>", "Mateusz Krzyziński <krzyzinskimateusz23@gmail.com>", "Paweł Fijałkowski <fijalkowskipablo@gmail.com>"]
license = "MIT"
repository = "https://github.com/pyartemis/artemis"
homepage = "https://github.com/pyartemis/artemis"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
exclude = [
    "venv_artemis/**",
    "artemis/venv_artemis/**",
    "*.egg-info/**",
    "build/**",
    "dist/**",
]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "2.2.2"
numpy = "2.0.2"
scikit-learn = "1.6.1"
seaborn = "0.13.2"
ipykernel = "^6.31.0"
tqdm = "^4.64.1"
networkx = "3.5"
matplotlib = "3.10.0"
pillow = "11.3.0"
pyzmq = "26.2.1"
tornado = "6.5.1"
traitlets = "5.7.1"
rich = "13.9.4"
psutil = "5.9.5"
decorator = "4.4.2"
docutils = "0.21.2"
nbformat = "5.10.4"
ray = "2.51.1"

[tool.poetry.dev-dependencies]
black = {version = "^22.10.0", allow-prereleases = true}
xgboost = "^1.7.1"
lightgbm = "^3.2.0"
parameterized = "^0.8.1"
pytest = "^7.2.0"
pdoc3 = "^0.10.0"
build = "^0.10.0"
twine = "^4.0.0"
debugpy = "1.8.15"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
